# Main metainfo
log_save_dir: './logs_full_ttsr_cufed5'

model_checkpoint_callback__monitor: ['avg_val_psnr', 'avg_val_ssim']
model_checkpoint_callback__save_top_k: 5
model_checkpoint_callback__mode: 'max'
baseline_composer: TTSRLitComposer
baseline_checkpoint: '/trinity/home/l.kulikov/projects/train-suite/logs_ttsr_cufed5/version_0/checkpoints/epoch=1-avg_val_psnr=23.6239-avg_val_ssim=0.6662.ckpt'
# model_checkpoint: '/trinity/home/l.kulikov/projects/train-suite/logs_full_ttsr_cufed5/version_3/checkpoints/epoch=4-avg_val_psnr=22.8431-avg_val_ssim=0.6491.ckpt'
composer: FullTTSRLitComposer

trainer__kwargs:
  max_epochs: 48
  track_grad_norm: 2
  # gradient_clip_val: .5
  precision: 16
  accelerator: 'dp'
  # fast_dev_run: True

# Model
model: 'TTSR'
model__kwargs:
  n_feats: 64
  num_res_blocks: 4+4+2+1
  res_scale: 1.

# Training
batch_size: 9
loss: 'rec+0.01*per+0.01*tper+0.001*adv'

optimizer: Adam
lr:
  MainNet: !!float 1e-4
  LTE: !!float 1e-5
optimizer__kwargs: 
  betas: [0.9, 0.999]
  eps: !!float 1e-8

lr_scheduler: StepLR
lr_scheduler__kwargs:
  step_size: 999999
  gamma: .5

add_vgg19: True
use_discriminator: True
discriminator: Discriminator
discriminator__args: [160]

discriminator__optimizer: Adam
discriminator__lr: !!float 1e-4
discriminator__optimizer__kwargs:
  betas: [0., 0.9]
  eps: !!float 1e-8

discriminator__lr_scheduler: null
discriminator__frequency: 2

# Datasets
train_dataset: 'CufedTrainDataset'
train_num_workers: 4
train_dataset__kwargs:
  dataset_dirpath: '/trinity/home/l.kulikov/data/cufed/train'

val_dataset: 'CufedTestDataset'
val_num_workers: 2
val_dataset__kwargs:
  dataset_dirpath: '/trinity/home/l.kulikov/data/cufed/test'
